### PR TITLE
Added gulp

### PR DESCRIPTION
**Pull request by ankemp**
I've gone ahead and added gulp to this repo.
Makes for minifying your file just a tad easier. :)

### CODE REVIEW

**Comment by tomhodgins** [comment]
I'm not a gulper, to convert it to the minified version I've been search & replacing variables and making some tweaks by hand, and using the Closure Compiler.

http://codegolf.github.io/codegolfIDE

This editor makes it easy to work with minifying and packing JavaScript as you edit, and you can use this tool to generate code on any device, including mobile :)

Hit the checkbox at the bottom of the file, or press Ctrl-⌥-S on OS X, or Shift-Alt-S on Windows to toggle the panel as well, that's where you can easily generate minified and packed code of what you're working on.

**Comment by ankemp** [comment]
Seems like a lot of extra work.

Wouldn't it be easier to just run "gulp" in your cmd line?

**Comment by zhouzi** [comment]
I have to agree that the process of minifying the source file should be automated and shouldn't require contributors to use a custom IDE with some configuration ^^

That been said, I think gulp is an overkill in this particular situation. You could go with an npm script and just use uglify: `uglifyjs dragon.js -o dragon.min.js`

**Comment by tomhodgins** [comment]
> `uglifyjs dragon.js -o dragon.min.js`

dragon.js is already the minified version of the dragon script on one line, I'm not sure what purpose uglifying it further would serve in this case.

Two ways I've been able to iterate faster this year have been to build smaller tools, and to use as much front-end tooling as I can so I'm not locked into any one computer or OS. I find that when it's easy to work from anywhere, I often find that the moments when I have to hack on this small-scale open-source stuff is mostly when I have an iPad and a few moments to tinker, so requiring Gulp, or NPM which need a command-line running on a computer would actively limit how and when I'm able to hack on my projects.

The web-based IDE I linked to doesn't require any configuration, and you can get to it equally from any OS or device, but no matter what tool you use - there's currently no step in my workflow right now that makes any suppositions about the device you're using to edit it. There's nothing I have to 'wait until I'm back at a computer' to do.

On a slightly different note, the bigger reason why I think hooking up a minifying script to this is overkill here is that:
- the repository is here to host a _one-line_ JS file
- that single line of JS has features intentionally added which minifiers remove

So not only would Gulp or NPM not accomplish the specific task I need to do, but it would severely limit the places and devices where I can do the wrong action from.

That is unless I took the time to build a minifier script which does what I want, and then figure out how to hook that up to NPM…but I don't think I'll be saving time this way.

At this scale, and with this featureset I consider dragon.js nearly complete because it does more than what I set out to create originally :)

Since dragon, I've done some [experiments with adding support for even more inline styles](http://codepen.io/tomhodgins/pen/ZQPRNE), written a small 8-line plugin that can [enable data backup of any input fields to localStorage](http://codepen.io/tomhodgins/pen/VeRxRY), and written a slideshow [introducing folks to element queries](http://elementqueries.com/notes/slides.html). Plus a whole ton of other stuff.

The only way you can iterate fast is by building things _small_ and ruthlessly eliminating dependencies, whether code dependencies or tool dependencies. I'm unencumbered by libraries or tools and free to produce anywhere I want - what could save time better than that? :D

**Comment by zhouzi** [comment]
Ok, I get the point and see what are your goals :) If you consider dragon.js to be "done", there is clearly no point to bother further. Automated tools are great when you need to build a distributed file several times and/or with different contributors but are probably not worth it for a one-time build.

**Comment by tomhodgins** [comment]
Thanks! Have you checked out the [other fork](https://github.com/tomhodgins/dragon/pull/3) of this - I think it's probably far more advanced than what I've got here right now. Some really cool stuff in there that's been added that I don't quite understand yet, I'm still working my way through his edits.

What kind of features would make it more useful to you?

**Comment by zhouzi** [comment]
Thanks, I'll have a look :)

Well, I do not have any special ideas about cool features but #3's list looks great (didn't have a look at the code though).

**Pull request closed without merging**
